### ISSUE TITLE
Program Details Screen

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#1]
Create a detailed screen for each open-source program, providing comprehensive information such as organizations, eligibility criteria, application process, and important dates etc

**Comment by Ansh-Gupta-Official** [comment]
Hi @andoriyaprashant,  

I can create detailed program info screen (organizations, eligibility, application, dates) for this project. 
Assign this task to me, i'll do my best!.

Thanks!

**Comment by andoriyaprashant** [comment]
Go ahead @Ansh-Gupta-Official

**Comment by Ansh-Gupta-Official** [comment]
> Go ahead @Ansh-Gupta-Official

Thanks, I'll do my best.

**Comment by Ansh-Gupta-Official** [comment]
Hi, Can you please elaborate more about it like what i actually have to do in it and what kind of UI and functionality it should be ?

**Comment by andoriyaprashant** [comment]
we want to use web scraping in this app so that the entire data of websites can be imported into this app, and I want this in every program.

These are demo screenshots showing how organizations and their details are displayed. Similarly, we want organizations and others to be displayed

![gssoc page opso](https://github.com/andoriyaprashant/OpSo/assets/121665385/23e93630-d9bd-4b88-b277-f1cb146b93bd)
![gsoc page opso](https://github.com/andoriyaprashant/OpSo/assets/121665385/fa76860d-f7c6-4422-b410-a28a171b89c0)

**Comment by Ansh-Gupta-Official** [comment]
then how i will get the api for showing data in the screens?

**Comment by himanshugoyal77** [comment]
you will require custom backend for web scraping

**Comment by Prashant-2024** [comment]
I would like to work on this issue under GSSOC'24.
Please assign it to me.
