### ISSUE TITLE
Feat:  Adding new Section called Articles

### ISSUE THREAD

**Issue by pavants777** [andoriyaprashant/OpSo#101]
### Describe the feature

In this section where articles of that program where Posted that can see by user ... and get information about that programs, If you find useful assign this issue for me .. i will work on this (New Feature) 

### Add ScreenShots

Not yet ... 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chekka-Mounika** [comment]
I want to work on this please assign me this issue

**Comment by Shubham-Zone** [comment]
assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant Can I work on this issue? I intend to implement the same method featured in the video, while also providing other relevant information(Minimum Eligibility Criteria, How to Register, Rewards/Stipends, etc) to help the users gain enough information about the program to get them started.

**Comment by andoriyaprashant** [comment]
Go ahead @RishavKumarSinha
