### ISSUE TITLE
Feat:Add Adeptive screen in the entire project using ScreenUtil pkg

### ISSUE THREAD

**Issue by yagnik2411** [andoriyaprashant/OpSo#106]
### Describe the feature

ADD screen unit  package in the project and change every widget and screen size using pkg

### Add ScreenShots

right now we do not have an adapative screen in the entire project

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by arun7kumarr** [comment]
I have good command on flutter and I'm a GSSOC contributor. I would like to work on this. Please assign me this issue.

**Comment by krishitapandey** [comment]
can I work on this issues @arun7kumarr  haven't done it yet

**Comment by krishitapandey** [comment]
Task is done

**Comment by yagnik2411** [comment]
where is the PR

**Comment by krishitapandey** [comment]
![Uploading Screenshot 2024-05-29 at 11.00.18 AM.png…]()
](url)

**Comment by krishitapandey** [comment]
![Screenshot 2024-05-29 at 11 00 56 AM](https://github.com/andoriyaprashant/OpSo/assets/64957867/f28f5484-6601-4480-8b7d-8095ed2b9142)
![Screenshot 2024-05-29 at 11 00 18 AM](https://github.com/andoriyaprashant/OpSo/assets/64957867/189be514-cce5-4075-9420-cd0c2df73327)
I have made the pr . you can check in this images
