### ISSUE TITLE
Feat: Implement Project Features for Google Summer of Code (GSoC)

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#117]
### Describe the feature

Enhance the functionality and user experience of the Google Summer of Code (GSoC) screen within our Dart application by implementing the features associated with GSoC projects for each year. This includes displaying project details, integrating year-specific data, and providing interactive elements for users to explore GSoC projects.

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Saumya-28** [comment]
I would like to work on this issue. Could you please assign it to me?
