### ISSUE TITLE
BUG: No projects available for Linux Foundation

### ISSUE THREAD

**Issue by ShashankDeepak** [andoriyaprashant/OpSo#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Problem
There is no project data available to show for the Summer of Bitcoins.

## Proposed Solution
Extract the project list from the [Linux Foundation](https://www.linuxfoundation.org/projects) website and arrange them in JSON file format.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShashankDeepak** [comment]
Please assign me this issue.

**Comment by andoriyaprashant** [comment]
@ShashankDeepak Why are you creating a new issue when there is already an issue open for LFX mentorship?

**Comment by ShashankDeepak** [comment]
@andoriyaprashant I thought that issue #89  was just for creating the UI, and since there was no project available to create the UI, I thought it would be better to raise an issue. As  fetching project lists and creating UI are both quite big tasks on their own.

**Comment by andoriyaprashant** [comment]
> @andoriyaprashant I thought that issue #89  was just for creating the UI, and since there was no project available to create the UI, I thought it would be better to raise an issue. As  fetching project lists and creating UI are both quite big tasks on their own.

Okay, so add the projects in this issue and create the UI for the LFX mentorship page in that other issue.

**Comment by ShashankDeepak** [comment]
@andoriyaprashant Okay, will do it accordingly.
