### ISSUE TITLE
Add Flutter Ci

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#12]

**Comment by Kochurii** [comment]
I am participating in GSSoC 2024 and I am interested in working on this issue. Could you please assign it me.

**Comment by andoriyaprashant** [comment]
Go ahead @Kochurii

**Comment by hariram62** [comment]
can u please assign this issue to me ?? I would like to contribute..

**Comment by woodwolfswee** [comment]
@andoriyaprashant Are asking to implement CI/CD pipeline in this application?

**Comment by andoriyaprashant** [comment]
> @andoriyaprashant Can you please provide a brief description on this issue?

This implementation will facilitate the automatic testing and deployment of our Flutter application, enhancing the stability and reliability of our development process. This addition carries significant value, streamlining our workflow, and elevating the overall quality of our application.

**Comment by hariram4862** [comment]
@andoriyaprashant  Hi. I have sem exams this week. Probably, I will continue contributing from 21st may. So, I kindly request you to hold me as assignee.

Thank you.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by Prashant-2024** [comment]
I would like to address this issue under GSSOC'24.
Request to assign it to me

**Comment by andoriyaprashant** [comment]
> I would like to address this issue under GSSOC'24. Request to assign it to me

Go ahead @Prashant-2024

**Comment by samarsajad** [comment]
@andoriyaprashant Please assignn me this issue under GSSOC 2024
