### ISSUE TITLE
BUG: Fix the search option 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Fix the search option in the Summer of Bitcoin screen so that it is clearly visible, similar to how it appears in other programs, even in dark mode
![Screenshot 2024-05-18 235540](https://github.com/andoriyaprashant/OpSo/assets/121665385/8044b209-6886-43f3-8872-34e50de8f2bd)

![Screenshot 2024-05-18 235618](https://github.com/andoriyaprashant/OpSo/assets/121665385/3e03bfac-8062-4666-b27d-875a36781805)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Saumya-28** [comment]
Hi @andoriyaprashant !
I would like to work on this issue. Could you please assign it to me?

**Comment by SumitPareek2401** [comment]
I already fixed this in the pull request #118  made by me. But this part has not merged in the main branch. You can check in the files changed.

**Comment by Dev-AyushTrivedi** [comment]
I can fix this issue can you please assign this to me @andoriyaprashant
