### ISSUE TITLE
 Addition of app release or app preview for the project

### ISSUE THREAD

**Issue by a-m-a-nkumar** [andoriyaprashant/OpSo#125]
### What's wrong with the existing documentation

There should be an app release or preview version of the project available, allowing users to quickly download and test the app's functionality on Android devices. This version will enable developers, testers, and stakeholders to easily access the app, review its features, and identify any issues or areas for improvement. Providing a preview or release version ensures efficient feedback and helps in refining the app before the final release.This helps in testing the app a lot easier.

Either there should be an app release file or a link to download the app.
The app download link should be given in README file.

### Add ScreenShots

![4](https://github.com/andoriyaprashant/OpSo/assets/99753046/3b2b75f6-d041-4804-bed4-3ca5e9ca586e)

or 

![3](https://github.com/andoriyaprashant/OpSo/assets/99753046/471d102a-7f79-4d90-9424-0214f4ee7dd9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
@a-m-a-nkumar Currently, this app is not fully ready. Once all the programs and features have been added, we will release it.
