### ISSUE TITLE
Feature : Timeline Feature for Program Tracking 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#128]
### Describe the feature

Implement a timeline feature in the OpSo App to enable contributors to view and track the timeline of each program, ensuring they are well-informed and never miss any important program updates or events.

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by RishavKumarSinha** [comment]
Can I work on this issue? I intend to create a timeline for each project, within their existing page, that provides information regarding the important dates/deadlines(much like the GSSoC website). Along with the above, I also wish to create a separate page in the menu to show a cumulative timeline showing the last date to apply for each open-source program.

**Comment by andoriyaprashant** [comment]
Go for it @RishavKumarSinha

**Comment by andoriyaprashant** [comment]
@RishavKumarSinha Commit these changes, and I'll review and merge them
