### ISSUE TITLE
BUG: Bottom overflowed in Summer of Bitcoin Screen

### ISSUE THREAD

**Issue by vijaymehrotra** [andoriyaprashant/OpSo#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Bottom overflowed by some pixels in Summer of Bitcoin Screen when opening the keyboard.

ScreenShots as follows: 

![Screenshot_1716373372](https://github.com/andoriyaprashant/OpSo/assets/115913159/b5cd38f4-4ede-4157-8e93-996288d6c275)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter

**Comment by saisurendra6** [comment]
Can you assign this issue to me.
