### ISSUE TITLE
Feat: Notification for Program Timeline

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#134]
### Describe the feature

Implement a notification feature in this app that alerts contributors about upcoming deadlines for open-source programs. This will help contributors stay informed about important dates and ensure they don't miss any opportunities to apply.

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant  , Can I work on this feature? I am not very familiar with implementing the notification feature, but I am interested in learning more about this and willing to give it my best try.
