### ISSUE TITLE
Feat: Implement Swipe Down Reload Feature for Each Program Screen

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#141]
### Describe the feature

We need to implement a reload feature for each program screen in the Opso app. The reload functionality should allow users to swipe down on any screen to refresh the content, resetting it to the normal state. This feature should be consistent across all open-source programs within the app.

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Saumya-28** [comment]
Hi @andoriyaprashant !
I would like to work on this issue. Could you please assign it to me?
