### ISSUE TITLE
Feat: Implement Multi-Select Filter Feature for Projects and Organizations

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#142]
### Describe the feature

We need to enhance the filter functionality in the Opso app to allow users to select multiple filters simultaneously when viewing projects and organizations. Users should be able to filter by more than one organization name and language name at the same time. This improvement will help users obtain more precise and relevant results, enhancing their overall experience.

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Saumya-28** [comment]
Hi @andoriyaprashant !
I would like to work on this issue. Could you please assign it to me?

**Comment by Shreya-Agarwal-Webanav** [comment]
I have worked as a Flutter Development intern and I am a GSSoC contributor, kindly assign me this issue.

**Comment by Saumya-28** [comment]
Hi @andoriyaprashant 
Kindly review the pr and let me know.
