### ISSUE TITLE
BUG: No BookMark button for some screens

### ISSUE THREAD

**Issue by vijaymehrotra** [andoriyaprashant/OpSo#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no option for adding bookmark in bitcoin and gsoc screen and in the bookmark page , the bookmark is not fully clickable.

Screenshots: 
![image](https://github.com/andoriyaprashant/OpSo/assets/115913159/3bbd96a6-b9fa-497f-99ab-3513d72be1cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
@vijaymehrotra I want this bookmarks feature to be available for projects as well. So far, this bookmark feature is only for programs.

**Comment by vijaymehrotra** [comment]
> @vijaymehrotra I want this bookmarks feature to be available for projects as well. So far, this bookmark feature is only for programs.

Yes , It will be done. 👍

**Comment by krishitapandey** [comment]
@andoriyaprashant  can I work on this issue as @vijaymehrotra  hasnt done it yet

**Comment by vijaymehrotra** [comment]
@krishitapandey I am working on it
