### ISSUE TITLE
Feat: UI Improvement for The Linux Foundation Page

### ISSUE THREAD

**Issue by Saumya-28** [andoriyaprashant/OpSo#164]
### Describe the feature

UI Improvement for the Linux Foundation Page for better user experience.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SumitPareek2401** [comment]
@andoriyaprashant can you also assign this issue to me?
