### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by samarsajad** [andoriyaprashant/OpSo#170]
### Describe the feature

Implementation of a splash screen feature for enhancing the user experience during app launch. This feature provides a visually appealing introductory screen, offering a seamless transition into the main application interface

### Add ScreenShots

![IMG-20240530-WA0012](https://github.com/andoriyaprashant/OpSo/assets/142666229/a0704601-2d5d-4c5d-809d-6b512f9a9179)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter
