### ISSUE TITLE
Feat: Social Winter of Code: Implementation of UI page for Social Winter of Code  

### ISSUE THREAD

**Issue by RishavKumarSinha** [andoriyaprashant/OpSo#173]
### Describe the feature

Under this Issue, I intend to complete the Social Winter of Code UI page along with the features already added to the project(Search, Bookmark, Timeline Update) for SWoC.

### Add ScreenShots

N.A.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
@RishavKumarSinha assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter
