### ISSUE TITLE
BUG: Excessive Loading Time for Google Summer of Code Screen

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The loading time for the Google Summer of Code screen is excessively long. This delay negatively impacts user experience and efficiency. 

https://github.com/andoriyaprashant/OpSo/assets/121665385/16ed0205-afdd-4ba2-9d6f-5aa8462aa855

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by vijaymehrotra** [comment]
Hello @andoriyaprashant 
Please assign this issue to me

**Comment by Shubham-Zone** [comment]
@andoriyaprashant  please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter
