### ISSUE TITLE
Implement UI Changes for Seamless Scrolling of Top Elements on Programs Screen

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we navigate to the programs screen where projects are displayed, we want the top elements like the year, filter, etc., to scroll as well. To achieve this, we need to make changes to the UI so that users can easily see all the projects and organizations.

https://github.com/andoriyaprashant/OpSo/assets/121665385/d015e076-5468-4ff7-9bfa-30970998df36

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by vijaymehrotra** [comment]
Hello @andoriyaprashant ,
Can I work on this issue

**Comment by Shubham-Zone** [comment]
@andoriyaprashant please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter

**Comment by Shubham-Zone** [comment]
@andoriyaprashant i am getting a error Error: Entrypoint isn't within the current project normally i resolved this issue many times but this time it is not resolved can you help me ?
