### ISSUE TITLE
BUG: Summer of Bitcoin screen

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "2023" button and its associated projects are not appearing on the Summer of Bitcoin screen.
![Screenshot_20240603_173657 1](https://github.com/andoriyaprashant/OpSo/assets/121665385/3c4a655d-b479-4cf5-ad54-809c2a5fdc43)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by vijaymehrotra** [comment]
Hello @andoriyaprashant ,
Can I work on this issue
