### ISSUE TITLE
Design a Logo for the project OPSO

### ISSUE THREAD

**Issue by MehtabAsHellic** [andoriyaprashant/OpSo#189]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by MehtabAsHellic** [comment]
@andoriyaprashant   do have any design style in the mind or I designed as new brand identity ? I will share some sample here soon

**Comment by andoriyaprashant** [comment]
@MehtabAsHellic We already have a logo for OpSo. If you have a new design, please let us know; otherwise, we will use the existing OpSo logo that has already been designed.

**Comment by MehtabAsHellic** [comment]
> f you have a new design, please let us know

ok
