### ISSUE TITLE
Feat: Implementing a chatbot feature for open source queries using Gemini

### ISSUE THREAD

**Issue by Saumya-28** [andoriyaprashant/OpSo#192]
### Describe the feature

Implementing a chatbot feature for open source queries using Gemini for better user engagement.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Go ahead @Saumya-28

**Comment by Saumya-28** [comment]
@andoriyaprashant please assign the level to this issue.
