### ISSUE TITLE
BUG: Linux foundation program screen 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Linux Foundation program screen is not working properly.
![image](https://github.com/andoriyaprashant/OpSo/assets/121665385/5631879d-c9a2-4265-9f3b-3af654996c38)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by RishavKumarSinha** [comment]
Can I work on this issue? I also would like to know if you want it such that images load faster, or I should remove the images and make it similar to other programs like GSSoC, SWoC, etc(adding more description to the projects)?
