### ISSUE TITLE
BUG: No projects found (Google summer of code screen )

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/andoriyaprashant/OpSo/assets/121665385/9502c8cb-c97e-4f4a-966d-b932f432189d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by vijaymehrotra** [comment]
Hello @andoriyaprashant 
Please assign this to me

**Comment by samarsajad** [comment]
Please assign this issue to me,sir @andoriyaprashant  I will create the request at the earliest .

**Comment by aikansh008** [comment]
Please assign this issue to me
