### ISSUE TITLE
Implement a search feature

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#2]

**Comment by Saumya-28** [comment]
I would like to work on this. Could you please assign this to me along with some description on this required feature?

**Comment by andoriyaprashant** [comment]
Hey @Saumya-28 
In this feature, I want there to be a search option on the home screen where all open-source programs are listed, enabling users to search for their programs. Instead of creating a search bar, I prefer adding a search icon through which users can search for open-source programs.
