### ISSUE TITLE
BUG: App crashes or stuck at black screen if notification permission is not given

### ISSUE THREAD

**Issue by ShashankDeepak** [andoriyaprashant/OpSo#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the application is launched and we don't provide the notification permission the app crashes or gets stuck on black screen.

## Video

https://github.com/andoriyaprashant/OpSo/assets/92669664/2e035585-15f8-436f-a738-e19e39742741

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShashankDeepak** [comment]
Please assign me this issue.

**Comment by andoriyaprashant** [comment]
@ShashankDeepak I would like you to remove the notification that always appears when opening the app for the first time, and use notifications only for important updates like program deadlines, not every time the app is opened
