### ISSUE TITLE
DOC: Add pull request template 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#22]
### What's wrong with the existing documentation

Na 

### Add ScreenShots

Add pull request template (path - .github)

![image](https://github.com/andoriyaprashant/OpSo/assets/121665385/8d34b55f-1bcb-42d6-87d3-94555095d726)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by hariram62** [comment]
i would like to contribute to this issue. Can u pls assign me ?

**Comment by andoriyaprashant** [comment]
Go for it @hariram62

**Comment by MrCodYrohit** [comment]
@andoriyaprashant Can you assign this task to me? I will follow all code of conducts of this project and will make sure to deliver a nice pull request template/document.

**Comment by andoriyaprashant** [comment]
> I would like to contribute in this issue, Can u pls assign me ???

Go ahead @mohammadaliyasin

**Comment by AnitSarkar123** [comment]
@andoriyaprashant sir can you please assign me this issue under GSSOC'24

**Comment by andoriyaprashant** [comment]
Go ahead @AnitSarkar123

**Comment by MrCodYrohit** [comment]
@andoriyaprashant Hey, i am at collage, thats why I dont able to reply, please assign this issue to me, I will try to fix it within 24 hours.

**Comment by andoriyaprashant** [comment]
@MrCodYrohit No problem, you can open the pull request, and I will review it

**Comment by MrCodYrohit** [comment]
@andoriyaprashant I fixed the issue by creating the contribution.md file, can you please see.

**Comment by andoriyaprashant** [comment]
@MrCodYrohit This issue is for the pull request template. 
 Please create a new issue to add the contributing file.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by Prashant-2024** [comment]
I would like to work on pull request template issue under GSSOC'24.
Please assign it to me
