### ISSUE TITLE
Feat: Add Hacktoberfest Program to OpSo

### ISSUE THREAD

**Issue by samarsajad** [andoriyaprashant/OpSo#231]
### Describe the feature

I want to add the Hacktoberfest program to OpSo, where all the information about this program will be displayed

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant , Can I work on this Issue? I intend to create another issue for the addition of projects and use it to complete the UI page for Hacktoberfest via this Issue.
