### ISSUE TITLE
Feat:Adding Learning path for complete beginners

### ISSUE THREAD

**Issue by Saumya-28** [andoriyaprashant/OpSo#233]
### Describe the feature

This feature will help students to find the relevant project and start their career in open-source

It will be a step by step process :
- When the person will in this section he will enter his domain and search for the good-first-issue
- He will be provided youtube videos for starting git  and github 
- Apply for any open-source program 
- Complete the journey

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aikansh008** [comment]
sir please assign this issue to me

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant , Can I work on this issue? I intend to create a quick flash-card-esque tutorial to help users make their first pull request via a quick GitHub Pull Request tutorial and help them find their first "good-first issue" to get them started with the open-source contribution.
