### ISSUE TITLE
BUG: Fix Incorrect Splash Screen Display

### ISSUE THREAD

**Issue by samarsajad** [andoriyaprashant/OpSo#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The splash screen currently displays incorrectly. This issue needs to be resolved to ensure the splash screen appears as intended.

![image](https://github.com/andoriyaprashant/OpSo/assets/142666229/173798e7-fb39-41d4-9cea-94ad4712cf47)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aikansh008** [comment]
please aasign this issue to me
