### ISSUE TITLE
Feat: Dark Mode 

### ISSUE THREAD

**Issue by mohammadaliyasin** [andoriyaprashant/OpSo#24]
### Describe the feature

Dark mode in an app is a setting that switches the interface from a light background with dark text (light mode) to a dark background with light text. It offers benefits like:

- **Reduced eye strain:** Easier on your eyes in low-light environments.
- **Battery savings:** Can potentially save battery life on devices.
- **Aesthetics:** Some users simply prefer the look of dark mode.

### Add ScreenShots

![Dark-Mode-Hero](https://github.com/andoriyaprashant/OpSo/assets/110727129/c8c54190-d7ac-4afa-8f4a-e717f80eeb9a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor

**Comment by andoriyaprashant** [comment]
@mohammadaliyasin Any Updates?

Add this Dark mode feature above the About section in the menu option that is already on the homepage

**Comment by krishitapandey** [comment]
Hello @andoriyaprashant  @mohammadaliyasin  has not solved the issue still . Can I do his part

**Comment by andoriyaprashant** [comment]
> Hello @andoriyaprashant  @mohammadaliyasin  has not solved the issue still . Can I do his part 

Go ahead @krishitapandey

**Comment by SumitPareek2401** [comment]
@andoriyaprashant assigned this issue to me and I will merge it quickly.

**Comment by Prashant-2024** [comment]
I have the required skills in flutter to implement dark mode.
Request to assign it to me under GSSOC'24

**Comment by andoriyaprashant** [comment]
> @andoriyaprashant assigned this issue to me and I will merge it quickly.

assigned @SumitPareek2401

**Comment by SumitPareek2401** [comment]
Do you have any suggestions for the UI or should I merge it? 

Video:

https://github.com/andoriyaprashant/OpSo/assets/122019171/43526a43-daef-4171-804f-dc77be9e7b5a

**Comment by andoriyaprashant** [comment]
@SumitPareek2401 Please change this button as shown in the screenshots. It will look better for the app

![Screenshot 2024-05-18 134154](https://github.com/andoriyaprashant/OpSo/assets/121665385/46185979-229e-470f-a5a5-a67b59be2177)

![Screenshot 2024-05-18 134213](https://github.com/andoriyaprashant/OpSo/assets/121665385/e5b17ae1-2f19-4014-8d41-095798910068)

**Comment by SumitPareek2401** [comment]
Now fine?
https://github.com/andoriyaprashant/OpSo/assets/122019171/bb6e6449-dff2-42c2-883c-f5571f09e305

**Comment by SumitPareek2401** [comment]
Now fine? 

Video:

https://github.com/andoriyaprashant/OpSo/assets/122019171/2cf31a06-7540-4583-9bc4-d38b2205d0a7

**Comment by andoriyaprashant** [comment]
> Now fine? 
> 
> 
> 
> Video:
> 
> 
> 
> https://github.com/andoriyaprashant/OpSo/assets/122019171/2cf31a06-7540-4583-9bc4-d38b2205d0a7
> 
> 
> 
> 

@SumitPareek2401 Place the switch theme button above the add bookmark button

**Comment by SumitPareek2401** [comment]
Done. I am going to merge it.
