### ISSUE TITLE
BUG: "Menu" text causes overflow in drawer

### ISSUE THREAD

**Issue by ShashankDeepak** [andoriyaprashant/OpSo#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Bug
The "Menu" text present in the drawer throws an overflow error and the placement is bad.

## Screenshot
![image](https://github.com/andoriyaprashant/OpSo/assets/92669664/3f31e66b-e849-49f5-93d2-f15aa51dabe2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vedanshi27vishu** [comment]
I want to solve this error. Please assign this error to me.

**Comment by andoriyaprashant** [comment]
Go ahead @Vedanshi27vishu

**Comment by Vedanshi27vishu** [comment]
@andoriyaprashant  Sir I have done it. Please have a look on it whenever you are free.
Thankyou....

**Comment by Vedanshi27vishu** [comment]
Sir I have committed pls check.
