### ISSUE TITLE
BUG: User text barely visible in chat bot page in dark mode

### ISSUE THREAD

**Issue by ShashankDeepak** [andoriyaprashant/OpSo#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Bug
When the user sends a text in the chatbot when a dark theme is used, the text is not visible. In the given screenshot you can see the text "hello" is barely visible.

## Screenshot
![image](https://github.com/andoriyaprashant/OpSo/assets/92669664/e4c382e1-c605-4c6d-8a0d-d9c4241e598b)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
@ShashankDeepak Any updates?

**Comment by Vedanshi27vishu** [comment]
Sir can you assign this issue to me.

**Comment by aikansh008** [comment]
sir please assign this issue to me

**Comment by Vedanshi27vishu** [comment]
The issue has been resolved. Kindly have a look whenever you are free.

**Comment by Vedanshi27vishu** [comment]
Isse is resolved sir. Please take a look.
