### ISSUE TITLE
Feat: Improve the UI

### ISSUE THREAD

**Issue by Antrimo** [andoriyaprashant/OpSo#25]
### Describe the feature

Hey,
I found that the UI is not same as given in the Description. Could you provide the UI/Figma file so as to code the same.
Improving it will make it look more attractive and smooth flow for the Users.

### Add ScreenShots

![image](https://github.com/andoriyaprashant/OpSo/assets/114746821/39cfd459-4504-43b9-89b2-d72a44260ec8)
![image](https://github.com/andoriyaprashant/OpSo/assets/114746821/e240434b-cd28-4aeb-99c8-c16a992c324d)
![image](https://github.com/andoriyaprashant/OpSo/assets/114746821/753d5934-9633-4235-9ffb-219ac6c76ac8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mohammadaliyasin** [comment]
I would like to work on this issue. Could you please assign me this issue???

**Comment by krishitapandey** [comment]
I am also interested in making changes on UI . can you assign also assign me this issue . 
GSSOC's 24 Contributor  I have an experience in flutter and I am interested in UI designing

**Comment by harsh6045** [comment]
Can you assign also assign me this issue. I am GSSOC's 24 Contributor. @Antrimo

**Comment by harsh6045** [comment]
Thanks for assigning working my best on the issue ..!!

**Comment by harsh6045** [comment]
I have created the pr. Kindly check
