### ISSUE TITLE
Feat: Redox OS: Addition of Project.

### ISSUE THREAD

**Issue by RishavKumarSinha** [andoriyaprashant/OpSo#250]
### Describe the feature

Under this Issue, I intend to extract the projects for Redox OS from https://www.redox-os.org/rsoc/ and arrange them in JSON file format, to implement the Redox OS Page.

### Add ScreenShots

![Screenshot 2024-07-14 104222](https://github.com/user-attachments/assets/ca1f0bae-85f2-4f12-bd98-9fe53e1f622f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aikansh008** [comment]
please assign this issue to me

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant , I need a few more days to get this done.
