### ISSUE TITLE
Feat: Implementation of UI page for Redox OS

### ISSUE THREAD

**Issue by RishavKumarSinha** [andoriyaprashant/OpSo#251]
### Describe the feature

Under this Issue, I intend to complete the Redox OS UI page along with the features already added to the project(Search, Bookmark, Timeline Update, Info Page) for Redox OS.

### Add ScreenShots

![Screenshot 2024-07-14 104222](https://github.com/user-attachments/assets/772b8f0a-1ce3-4c69-8b94-4ff16e7cdb76)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aikansh008** [comment]
please assign this issue to me

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant , I need a few more days to get this done.
