### ISSUE TITLE
BUG: Incomplete navigation in about section

### ISSUE THREAD

**Issue by Mohanish-25** [andoriyaprashant/OpSo#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The GitHub and Gssoc Website buttons in the about sections do not work, they lack the redirect feature

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mohammadaliyasin** [comment]
I would like to work on this issue.
Could you please assign me this issue???
