### ISSUE TITLE
Feat: Add GirlScript Winter of Code Program

### ISSUE THREAD

**Issue by samarsajad** [andoriyaprashant/OpSo#279]
### Describe the feature

Integrate information about the GirlScript Winter of Code program into the app.

### Add ScreenShots

na

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
Hello @andoriyaprashant Please assign these issues to me: #272, #273, #274, #275, #276, #277, #278, #279, #280, #281, and #282 
Thank you

**Comment by andoriyaprashant** [comment]
> Hello @andoriyaprashant Please assign these issues to me: #272, #273, #274, #275, #276, #277, #278, #279, #280, #281, and #282 Thank you

Hello @samarsajad  I have assigned these issues to you. However, please try to open  pull requests as soon as possible because after the 31st, no pull requests will be counted if you are a GSoC contributor.

**Comment by RishavKumarSinha** [comment]
Hi, Can I work on this issue?
