### ISSUE TITLE
Feat:Add pages after clicking nav bar 

### ISSUE THREAD

**Issue by krishitapandey** [andoriyaprashant/OpSo#29]
### Describe the feature

There is no page after clicking on Nav bar on top right and  the git and website link in about page doesn't direct you to the respective page 

### Add ScreenShots

![Uploading Screenshot 2024-05-11 at 6.45.28 PM.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragJoshi05** [comment]
Title: Feat: Add pages and fix links in navigation bar

Description:
Hi @krishitapandey, **I'd like to tackle this issue.** I'll create pages for each nav bar option and fix the links on the about page. Ready to start ASAP. **GSSOC'24 participant**. Thanks!

**Comment by anuragJoshi05** [comment]
**Please assign me this issue, I will solve this issue surely**

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor
