### ISSUE TITLE
Feat: Implementation of UI Page for FOSSASIA Codeheat

### ISSUE THREAD

**Issue by RishavKumarSinha** [andoriyaprashant/OpSo#293]
### Describe the feature

Under this Issue, I intend to complete the FOSSASIA Codeheat UI page along with the features already added to the project(Search, Bookmark, Timeline Update, Info Page) for FOSSASIA Codeheat Program.

### Add ScreenShots

![Screenshot 2024-08-02 074724](https://github.com/user-attachments/assets/fc2e9293-fdaf-4841-aaf8-bbfea3994b2f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aikansh008** [comment]
Please assign this issue to me

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant , can you let me know whether I can get started on these issues?
