### ISSUE TITLE
Add filtering options

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#3]

**Comment by Saumya-28** [comment]
I would like to work on this, please assign me this issue.

**Comment by andoriyaprashant** [comment]
go for it @Saumya-28

**Comment by Saumya-28** [comment]
Hi @andoriyaprashant 
Could you please explain me what kind of filters you want?

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor
