### ISSUE TITLE
Feat: Add GSoC Program Projects for Multiple Years

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#305]
### Describe the feature

We need to extend the existing structure for GSoC projects to include data for multiple years, including but not limited to 2024, 2023, 2022, 2021, and 2020.

**Current Structure:**
A folder named assets/projects/gsoc_projects has been created, containing a file named gsoc24projects.json for GSoC 2024 program projects.

**Required Changes:**
Add JSON files for GSoC projects from previous years (e.g., gsoc23projects.json, gsoc22projects.json, etc.) in the assets/projects/gsoc_projects folder.

Ensure each file follows the same format as gsoc24projects.json.

Update any relevant code or documentation to accommodate the new files.

This will help in maintaining a comprehensive list of GSoC projects across different years, making it easier to reference past projects.

### Add ScreenShots

na

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by samarsajad** [comment]
please assign me this @andoriyaprashant

**Comment by RishavKumarSinha** [comment]
Can I work on this issue?
