### ISSUE TITLE
Feat: Refactor Program Navigation to Support Dynamic Program List

### ISSUE THREAD

**Issue by anuragJoshi05** [andoriyaprashant/OpSo#31]
### **Description:**

**Problem:** The current implementation in the OpSo application hardcodes the navigation logic for each program option. This approach limits scalability and maintainability as new programs are added or existing ones are modified.

Solution: I propose refactoring the program navigation to support a dynamic program list. This would involve dynamically generating program options based on a list of programs.

### **Benefits:**

Scalability: Easily add or modify programs without modifying the navigation logic.
Maintainability: Reduce code duplication and make future updates simpler and less error-prone.
Flexibility: Enable dynamic program listing, enhancing user experience and application adaptability.

### **Proposed Changes:**

Create a Program class to represent program data, including title and image asset path.
Define a list of programs and populate it with program data.
Update the HomePage widget to generate program options dynamically based on the list of programs.
Update the ProgramSearchDelegate to utilize the list of programs for search suggestions.
Refactor the navigation logic to navigate based on the selected program from the dynamic program list.

### Add ScreenShots

**Proposed Dynamic Program List:** ![WhatsApp Image 2024-05-11 at 21 44 51_4e120630](https://github.com/andoriyaprashant/OpSo/assets/148903459/56a285b9-8023-4033-804c-6cec5977f457)
   *Description: Visual representation of how the dynamic program list should appear in the application.*

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragJoshi05** [comment]
Kindly assign me this issue

**Comment by andoriyaprashant** [comment]
> Kindly assign me this issue

Go ahead @anuragJoshi05
