### ISSUE TITLE
BUG: Nav Button in Bookmark Section is not working.

### ISSUE THREAD

**Issue by RishavKumarSinha** [andoriyaprashant/OpSo#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Navigation Button to the respective programs is not working in case for Hacktoberfest, Google Summer of Code & Season of KDE. 

![Screenshot 2024-10-03 202959](https://github.com/user-attachments/assets/d586fa3f-7573-4296-b680-ad29f44eafa7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ritik6559** [comment]
I am a contributor at girl script summer of code i can fix the issue, can you assign it to me?
