### ISSUE TITLE
BUG: Information icon is missing.

### ISSUE THREAD

**Issue by itskundanhere** [andoriyaprashant/OpSo#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![github expert](https://github.com/user-attachments/assets/aae37065-cdf9-448c-9aaf-e26f83efbc65)
![hacktober fest](https://github.com/user-attachments/assets/0f97fd6f-74ef-4b65-a8f3-626fbd8584b4)
![gsoc](https://github.com/user-attachments/assets/261fb468-51e2-4fe1-97b8-998c339c0f7d)

The information icons are missing in the Hacktoberfest and GitHub Campus Expert sections, while the rest of the sections have the information icons.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Hello @itskundanhere  there’s no need for an info icon on these pages because, in other projects like GSoC, GSoD, etc., we had to add one since the projects were listed there. However, if you want to add any additional information to these pages, you can do so
