### ISSUE TITLE
DOC:  Enhance README with Troubleshooting Section

### ISSUE THREAD

**Issue by vaishnavipal1869** [andoriyaprashant/OpSo#332]
### What's wrong with the existing documentation

The current README lacks a troubleshooting section that addresses common bugs users may encounter. Adding this section would enhance user experience by providing guidance on resolving issues like search functionality and filter malfunctions.
**Suggested Additions:**
1. Troubleshooting Section: 
 Let's enhance the README by adding a Troubleshooting section. This will help users quickly find solutions to common issues they might encounter while using the application. It would be great to list some common problems along with their solutions. Additionally, we can mention any known limitations of the application to set clear expectations.

2. Visual Aids:
Incorporating relevant screenshots will greatly improve the clarity of our documentation. These visuals can help users understand the context better and navigate the application more effectively. Let’s make sure to include screenshots that highlight key features or showcase issues.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vaishnavipal1869** [comment]
I’d love to take on this task! Could you please assign me to this issue?

Thank you!

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
And please add gssoc-ext label
