### ISSUE TITLE
Feat: Add Webview

### ISSUE THREAD

**Issue by SatwikMohan** [andoriyaprashant/OpSo#34]
### Describe the feature

The WebView feature will allow loading the URLs for the particular links given. On clicking the particular option will allow loading the URL within the application.

### Add ScreenShots

Here is the media 
![WhatsApp Image 2024-05-12 at 11 49 29](https://github.com/andoriyaprashant/OpSo/assets/101632079/212ca132-dada-4cc2-859e-bba8c11e088f)
![WhatsApp Image 2024-05-12 at 11 49 28](https://github.com/andoriyaprashant/OpSo/assets/101632079/ceb4461a-ca8e-4348-adce-23edeee8d256)

https://github.com/andoriyaprashant/OpSo/assets/101632079/e90e4b19-2fb8-4339-94d2-623098543f6d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Hello @SatwikMohan  we want all the data of projects or programs to be displayed in this app rather than having to visit websites. You can add a separate feature for webview, where if a user wants to go to the website of that program, they can. However, we prefer that all the data be shown within this app, and that too with a proper UI.

**Comment by SatwikMohan** [comment]
Hello @andoriyaprashant I was working on the issue and tried scraping the websites but scrapping data is not working for all the website. Can you please suggest some alternative or shall I stick with scrapping of website to see if I can figure out some alternative.

**Comment by SatwikMohan** [comment]
Hello @andoriyaprashant I have figured out a method to load the html data for a website but for that I need to create an API in Node JS to return the HTML for dynamic website which cannot be loaded completely using packages after that by using the API in the flutter app I can scrap the data. Shall I proceed with this method?
