### ISSUE TITLE
DOC: Add contributors to README automatically

### ISSUE THREAD

**Issue by jvkousthub** [andoriyaprashant/OpSo#342]
### What's wrong with the existing documentation

There is no space for contributors, it can be added

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jvkousthub** [comment]
@andoriyaprashant I am a GSSoC'24 and Hactoberfest contributor assign me this issue

**Comment by andoriyaprashant** [comment]
Hello @jvkousthub 
I dont think we need this 
Thank you
