### ISSUE TITLE
BUG: title alignment issue in the appbar

### ISSUE THREAD

**Issue by WednesdaySP** [andoriyaprashant/OpSo#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the titles of all the pages are not aligned in center and also for moving back the default back arrow is used rather  a customized ios arrow should be used to enhance the UI of application.
![WhatsApp Image 2024-10-08 at 23 43 16_e311a341](https://github.com/user-attachments/assets/bcb143db-ace5-4fa5-8b37-d763b5cb55d8)
![WhatsApp Image 2024-10-08 at 23 43 16_cf7896d2](https://github.com/user-attachments/assets/4432883c-090f-432d-ac2b-74a390c91bc2)
![WhatsApp Image 2024-10-08 at 23 43 17_56092308](https://github.com/user-attachments/assets/4f6b58af-f6d8-4f75-ae3c-9bb90b3e6bc4)
![WhatsApp Image 2024-10-08 at 23 43 17_77dc440e](https://github.com/user-attachments/assets/7c3f1896-4166-4811-8d4e-0d75ac9dbca5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by WednesdaySP** [comment]
@andoriyaprashant I would like to fix this issue, please assign me, with all the required labels.

**Comment by WednesdaySP** [comment]
@andoriyaprashant please add level label also

**Comment by andoriyaprashant** [comment]
> @andoriyaprashant please add level label also

Hello @WednesdaySP I add the 'levels' tag after reviewing the pull request 👍🏻

**Comment by WednesdaySP** [comment]
@andoriyaprashant  ok
