### ISSUE TITLE
Feat: Add Search option in FAQs page

### ISSUE THREAD

**Issue by aashika-j18** [andoriyaprashant/OpSo#356]
### Describe the feature

I believe adding a search functionality in the FAQs page would improve user experience and accessibility.
Why?
Because, when I was using the app, it felt like there were multiple FAQs in the page. So it was difficult to refer to a particular question. 

### Add ScreenShots

![WhatsApp Image 2024-10-11 at 18 17 22_8adfd8f6](https://github.com/user-attachments/assets/12283104-6ee9-41b3-9c20-bcdb696429d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Go ahead @aashika-j18
