### ISSUE TITLE
Add contributors profile in readme

### ISSUE THREAD

**Issue by Aditijainnn** [andoriyaprashant/OpSo#358]
### Describe the feature

add contributors profile in readme

### Add ScreenShots

assign this to me under gssoc ext

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Hello @Aditijainnn I dont think we need this 
Thanks for contributing
