### ISSUE TITLE
BUG: Failed to view full content in Hyperledger screen

### ISSUE THREAD

**Issue by rishabh7923** [andoriyaprashant/OpSo#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/user-attachments/assets/6199a040-c6a8-4a4f-a4a8-40358a5e95e8

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Go ahead @rishabh7923
