### ISSUE TITLE
Feat:  Implement a sliding navigation bar to replace the existing menu option on the home screen 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#37]
### Describe the feature

Replace the current static menu option on the home screen of our Flutter app with a sliding navigation bar for improved navigation experience. The sliding navigation bar should seamlessly integrate with the existing UI and provide access to various app sections with smooth sliding animation.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Saumya-28** [comment]
Hi @andoriyaprashant !
I would like to work on this issue.
Could you please assign me this issue?

**Comment by andoriyaprashant** [comment]
@Saumya-28 I am assigning you this issue, but try to work on the previous issues assigned to you and open pull requests for them as well 👍🏻

**Comment by Saumya-28** [comment]
@andoriyaprashant 
It would be very helpful if you could provide me with some more clarification on the requirement.

**Comment by krishitapandey** [comment]
Hi @andoriyaprashant ,Can I work on this issue . I have done the previous issuse

**Comment by andoriyaprashant** [comment]
@Saumya-28 Currently, our menu option opens like a screen. I want to implement a sliding navigation bar to replace the existing menu option on the home screen

**Comment by Saumya-28** [comment]
@andoriyaprashant So basically instead of the vertical arrangement of the organization options in the menu screen, u want a sliding menu? Something like a sliding carousel for the options i suppose?

**Comment by krishitapandey** [comment]
@andoriyaprashant  can I work on this . I am GSSOC's contributor .

**Comment by andoriyaprashant** [comment]
> @andoriyaprashant So basically instead of the vertical arrangement of the organization options in the menu screen, you want a sliding menu? Something like a sliding carousel for the options i suppose?

@Saumya-28  Maybe I couldn't explain this feature properly to you. I wanted a sliding navigation bar that includes options for the about page, bookmarks screen, etc. However, you converted the home screen option into a sliding animation

![image](https://github.com/andoriyaprashant/OpSo/assets/121665385/4157c685-c9a2-44a4-8b1e-711357b24b9c)

**Comment by Prashant-2024** [comment]
I have understood the issue clearly regarding implementing sliding navigation bar.
Request to assign it to me under GSSOC'24
