### ISSUE TITLE
BUG: "Google Summer of Code" screen is not working as expected

### ISSUE THREAD

**Issue by rishabh7923** [andoriyaprashant/OpSo#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

GSOC screen has following issue:
- Year Filter does not work as expected
- It takes too much time to load the screen
- Refresh button reset the selected year and come backs to default year

Similar to #319 , But created new issue due to inactivity 

### Screenshot

https://github.com/user-attachments/assets/b11718bf-06a6-40b8-8083-e4eebc74919c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rishabh7923** [comment]
@andoriyaprashant is there a reason for not working on this issue

**Comment by andoriyaprashant** [comment]
Hello @rishabh7923 
Google Summer of Code has the most issues, and the screen for this program has been running on the API until now. I've also added organizations from past years in assets/projects/gsoc_org, and GSoC projects are in assets/projects/gsoc_projects. If you want, you can fetch data from these JSON files to display it on the GSoC screen. If the JSON data doesn’t work correctly, use the API to fix the screen. If you need any guidance, feel free to ask

**Comment by andoriyaprashant** [comment]
Go ahead @rishabh7923
