### ISSUE TITLE
DOC: Table Formatting (Open Source Programs Section) 

### ISSUE THREAD

**Issue by dipak2005** [andoriyaprashant/OpSo#373]
### What's wrong with the existing documentation

The table displaying "GSSOC 2024" lacks proper alignment and structure.
I can solve this issues.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Hello @dipak2005 
I dont think we need this 
Thanks for contributing
