### ISSUE TITLE
Feat: Create Logo for OpSo

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#38]
### Describe the feature

We need a unique and visually appealing logo for our Flutter app "OpSo". The logo should effectively represent the app's identity and purpose, reflecting its key features and target audience

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Pra-kas** [comment]
I'm a GSSOC'24 contributor, I'm eager to contribute to this issue.Please assign me.

**Comment by Khanishsuresh** [comment]
Hii @andoriyaprashant ,

As a GSSOC contributor, I'm interested in contributing to your project. 
Would you please assign me to your project under GSSOC 24?
