### ISSUE TITLE
BUG: Open summer of code 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/32015855-78a3-4df3-8ab4-3415dcaecf52)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by rishabh7923** [comment]
Assign me this issue :)
