### ISSUE TITLE
Feat: Add gsoc projects from assets/projects/gsoc_projects in gsoc program screen 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#399]
### Describe the feature

 Add gsoc projects 

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by rishabh7923** [comment]
I would love to work on this but how exactly would you like to show these projects? we have organization listed on that page. should we replace org with project?

**Comment by andoriyaprashant** [comment]
> I would love to work on this but how exactly would you like to show these projects? we have organization listed on that page. should we replace org with project?

@rishabh7923 I want both the organization list and the projects to be displayed. I’ve added the projects in the assets/projects/gsoc_projects JSON file, and those should be listed on the GSOC page. We’ll need to work on the UI since both the organizations and projects are important for GSOC. If any issues come up, feel free to ask 👍🏻

**Comment by rishabh7923** [comment]
how about i make 2 tabs inside the page, one that shows org and one that shows projects?

**Comment by andoriyaprashant** [comment]
> how about i make 2 tabs inside the page, one that shows org and one that shows projects?

The main GSOC website has a button that allows users to view projects, so you could add a similar button here alongside the GSOC organization list. This button should navigate directly to the GSOC projects page, making it easier for users to access the projects

**Comment by rishabh7923** [comment]
ok cool
