### ISSUE TITLE
 Implement push notifications

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#4]

**Comment by Saumya-28** [comment]
I would like to work on this issue.
Could you please assign me this issue?

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor

**Comment by Saumya-28** [comment]
Hi @andoriyaprashant 
I wanted to know which type of notifications are required. Please provide me with more details.
