### ISSUE TITLE
Adding past programs

### ISSUE THREAD

**Issue by Pra-kas** [andoriyaprashant/OpSo#40]
### Describe the feature

By adding the 'Adding Past Programs' feature, users can easily check out details and info from past programs. This expands the platform's collection, giving users useful historical info about projects.

### Add ScreenShots

In the right drawer,we can add a section dedicated to past programs. Users can conveniently access project information from previous programs, making it easy to review.
![Screenshot from 2024-05-12 14-17-42](https://github.com/andoriyaprashant/OpSo/assets/103827847/3ee26fcd-f347-4371-81bd-6280ed47d02a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by anvithagowda098** [comment]
Please assign this to me. 
I promise to adhere to code of conduct of the project. 
I'm a GSSoC '24 contributor.
I want to work on this issue.

**Comment by krishitapandey** [comment]
Can I work on this issue as @Pra-kas  has not done it 

I'm a GSSoC '24 contributor.
I want to work on this issue.

**Comment by Pra-kas** [comment]
@andoriyaprashant  @yagnik2411 Sir i have added past program page.

[Screencast from 2024-05-29 18-53-12.webm](https://github.com/andoriyaprashant/OpSo/assets/103827847/b1e591dd-4815-46fb-8e3e-8b65b7c581f1)
