### ISSUE TITLE
Feat: Adding logo for the app

### ISSUE THREAD

**Issue by Vanshikaxxa** [andoriyaprashant/OpSo#42]
### Describe the feature

 It'll  serves as a symbolic representation of your app's identity and can convey its purpose or personality at a glance.

### Add ScreenShots

![WhatsApp Image 2024-05-12 at 15 40 26_74a66e70](https://github.com/andoriyaprashant/OpSo/assets/133578313/eb749cd2-679e-43d8-b4f6-f172a1411c63)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me

**Comment by andoriyaprashant** [comment]
Any Updates? @Vanshikaxxa

**Comment by Vanshikaxxa** [comment]
yus sir i have created the logo

**Comment by andoriyaprashant** [comment]
@Vanshikaxxa  If the logo is complete, open a pull request, and I'll review it and merge it.
