### ISSUE TITLE
Feat:Button size

### ISSUE THREAD

**Issue by krishitapandey** [andoriyaprashant/OpSo#46]
### Describe the feature

The size of the button looks big . can I change it 

### Add ScreenShots

![Screenshot 2024-05-12 at 5 38 52 PM](https://github.com/andoriyaprashant/OpSo/assets/64957867/54c66ff5-e8f2-49d5-9570-1da486bd6852)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mohib-UL-Rehman** [comment]
hi @andoriyaprashant , can you please assign this issue to me ?

**Comment by krishitapandey** [comment]
I have made the changes and send u pr  @andoriyaprashant
