### ISSUE TITLE
BUG: No projects available for Google Season of Docs 

### ISSUE THREAD

**Issue by ShashankDeepak** [andoriyaprashant/OpSo#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description 
As of now when we click on Google Season of Docs no project is displayed

## Proposed Solution 
Extract information from [Google Season of Docs](https://developers.google.com/season-of-docs/docs/2023/participants) project website into JSON file year-wise. Use this JSON data to display different projects on the app.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShashankDeepak** [comment]
Please assign me this issue.

**Comment by andoriyaprashant** [comment]
@ShashankDeepak First, gather all the projects that exist and bring them into this project in JSON format. Then, create another issue where you can display those projects within the project. This will also solve the issue of your points.

**Comment by ShashankDeepak** [comment]
@andoriyaprashant Ok will do it
