### ISSUE TITLE
Feat: Add an Splash Page

### ISSUE THREAD

**Issue by krishitapandey** [andoriyaprashant/OpSo#56]
### Describe the feature

Addition of an Splah Page at the start representing the logo and welcoming the user . Here I have made the ui with different colors . please choose the color for the ui 

### Add ScreenShots

![Screenshot 2024-05-13 at 5 30 47 PM](https://github.com/andoriyaprashant/OpSo/assets/64957867/06a88227-c337-4053-a3b6-b8efafcd7fee)
![Screenshot 2024-05-13 at 5 31 19 PM](https://github.com/andoriyaprashant/OpSo/assets/64957867/e9b7716b-1b92-4e71-b3f7-9491f94fef51)
![Screenshot 2024-05-13 at 5 31 31 PM](https://github.com/andoriyaprashant/OpSo/assets/64957867/4f862a1c-3622-4c57-8deb-c31e39687644)
![Screenshot 2024-05-13 at 5 32 09 PM](https://github.com/andoriyaprashant/OpSo/assets/64957867/88d7f507-8fd5-4280-97d7-d45075350c8e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chekka-Mounika** [comment]
I want to work on this issue. Please assign me this issue

**Comment by andoriyaprashant** [comment]
@krishitapandey you can now work on this issue as you have the logo for the OpSo app. I am removing this issue from hold

**Comment by krishitapandey** [comment]
Can you choose the design .
