### ISSUE TITLE
Feat: Add a login screen

### ISSUE THREAD

**Issue by naikkajal** [andoriyaprashant/OpSo#66]
### Describe the feature

Add a login screen with options for email/password sign-in. Can also add the logo of the app at top.

### Add ScreenShots

![login](https://github.com/andoriyaprashant/OpSo/assets/144620204/97782f9f-7ff9-4350-ab1f-6d928ae92e80)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
@naikkajal We don't want to add the login or signup feature to this app. This is an open-source program, and we want everyone to be able to access it, regardless of who they are, and learn about the program. The login and signup feature is not needed right now.
