### ISSUE TITLE
Feat: Adding landing page for the application

### ISSUE THREAD

**Issue by Pra-kas** [andoriyaprashant/OpSo#73]
### Describe the feature

Developing a landing page for this application will offer visitors an engaging and informative introduction about this application.

### Add ScreenShots

Currently, this application starts with the following page. Adding a captivating landing page would be even more beneficial.
![Screenshot from 2024-05-14 19-10-16](https://github.com/andoriyaprashant/OpSo/assets/103827847/36826b2b-0572-44e3-a7dc-5b3f87ad9aac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by yagnik2411** [comment]
do you want to work on it? @Pra-kas

**Comment by Pra-kas** [comment]
Yes sir @yagnik2411 .

**Comment by yagnik2411** [comment]
what your plan for landing page

**Comment by Pra-kas** [comment]
@yagnik2411 we can have some quotes or animations or images that should mean core idea of application.

**Comment by yagnik2411** [comment]
@Pra-kas  start working on it

**Comment by Prashant-2024** [comment]
I would like to work on this issue under GSSOC'24. I have the required skill to implement welcome page.
Request to assign it to me.

**Comment by yagnik2411** [comment]
If it is not done in 4-5 by @Pra-kas the. I will assign you.

**Comment by Pra-kas** [comment]
@yagnik2411  @andoriyaprashant Sir i have completed landing page.
If i need to update anything in below page. I am ready to do so.

![Screenshot from 2024-05-16 23-49-12](https://github.com/andoriyaprashant/OpSo/assets/103827847/6a047c8d-d614-4c88-848e-df48bebce987)

**Comment by yagnik2411** [comment]
@Pra-kas good work

**Comment by yagnik2411** [comment]
@Pra-kas make pr of this
