### ISSUE TITLE
Feat:Implementing the GSoD page

### ISSUE THREAD

**Issue by SumitPareek2401** [andoriyaprashant/OpSo#75]
### Describe the feature

This Project requires the implementation of the GSoD Page for further user engagement and content.

### Add ScreenShots

![gsod](https://github.com/andoriyaprashant/OpSo/assets/122019171/8591a55b-13e3-4585-9a5b-490c0ec0cfa0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by yagnik2411** [comment]
@SumitPareek2401 if you have new idea you should tell first

**Comment by andoriyaprashant** [comment]
@SumitPareek2401 I am closing this issue because @ShashankDeepak  has already added it #71
