### ISSUE TITLE
BUG: wrong position of circular progress indicator

### ISSUE THREAD

**Issue by himanshugoyal77** [andoriyaprashant/OpSo#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the circular progress indicator is in the top left corner, i want to center it

![image](https://github.com/andoriyaprashant/OpSo/assets/92782099/af95ac47-e042-4a65-9388-2dfcd7ef3f92)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by yagnik2411** [comment]
Already done
