### ISSUE TITLE
BUG: fix the Ui of GSOD screen 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/andoriyaprashant/OpSo/assets/121665385/8348a4e7-19e9-42b8-9ccd-a25fdf2bbc82)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SumitPareek2401** [comment]
@andoriyaprashant Please assign this issue to me. I would like to work on it.

**Comment by SumitPareek2401** [comment]
https://github.com/andoriyaprashant/OpSo/assets/122019171/bcb116bc-d687-4646-8479-79f2a8dbbb20

Any suggestion for changing the UI of this screen or it is suitable?

**Comment by andoriyaprashant** [comment]
@SumitPareek2401  No, this is fine. Go ahead and open the pull request. I will review the changes in the code and then merge it.

**Comment by SumitPareek2401** [comment]
okay
