### ISSUE TITLE
Add Code of conduct file 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/OpSo#8]

**Comment by Saumya-28** [comment]
Hi @andoriyaprashant !
I would like to work on this issue as I have previously worked with quality documentations as well as written articles on medium. Could you please assign me this issue?

**Comment by khushi-saxena** [comment]
Hi @andoriyaprashant 
Can I add the Code of Conduct file as I have worked with documentation before?
Could you please assign me this issue?

**Comment by andoriyaprashant** [comment]
Go ahead @Saumya-28
