### ISSUE TITLE
Feat: Implementing the MLH page

### ISSUE THREAD

**Issue by SumitPareek2401** [andoriyaprashant/OpSo#81]
### Describe the feature

This Project requires the implementation of the Major League Hacking Fellowship Page for further user engagement and content.

### Add ScreenShots

![mlh](https://github.com/andoriyaprashant/OpSo/assets/122019171/d2f3d598-7d15-416a-a304-e70c0c9af926)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pavants777** [comment]
@andoriyaprashant assign this issue for me i will complete this issue

**Comment by krishitapandey** [comment]
@andoriyaprashant  can I work on this issue as @SumitPareek2401  hasn't done it yet 
I'm GSSOC's contributor
