### ISSUE TITLE
BUG: Year Buttons on GirlScript and GSoD page are un-scrollable.

### ISSUE THREAD

**Issue by RishavKumarSinha** [andoriyaprashant/OpSo#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On pages GirlScript and GSoD in web view, the year buttons are un-scrollable which hinders the user's capability of accessing the buttons.

![Screenshot 2024-05-15 163718](https://github.com/andoriyaprashant/OpSo/assets/136772607/b31863b3-fcab-461f-90eb-a4bfbb708d56)

I intend to fix this by removing the below line of code to make them scrollable.

![Screenshot 2024-05-15 165438](https://github.com/andoriyaprashant/OpSo/assets/136772607/4a66c59f-9323-455a-bddd-1d4c5076fe4c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
@RishavKumarSinha If you're opening an issue, please wait until it's assigned to you before submitting a pull request. This issue was opened previously #79   , so please follow the guidelines of this project

**Comment by RishavKumarSinha** [comment]
> @RishavKumarSinha If you're opening an issue, please wait until it's assigned to you before submitting a pull request. This issue was opened previously #79 , so please follow the guidelines of this project

Oh ok, I somehow missed this issue being mentioned in another Issue. I will make sure to follow the guidelines more strictly from now on.
