### ISSUE TITLE
Feat: Implementing UI for The Linux Foundation Page

### ISSUE THREAD

**Issue by Saumya-28** [andoriyaprashant/OpSo#89]
### Describe the feature

The UI for the Linux Foundation Page has not been implemented yet. 

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShashankDeepak** [comment]
Please assign me the issue
