### ISSUE TITLE
BUG: Outreachy Page not available

### ISSUE THREAD

**Issue by Prashant-2024** [andoriyaprashant/OpSo#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no dedicated page for Outreachy Program.

I would like to work on this issue under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pavants777** [comment]
@andoriyaprashant  assign this issue i would like to work on this issue...

**Comment by Prashant-2024** [comment]
Acknowledge

**Comment by Prashant-2024** [comment]
Update:
Few more tweaks are remaining on the page, will be sharing soon

**Comment by krishitapandey** [comment]
@Prashant-2024  can I work on this issue as @Prashant-2024  hasn't yet updated it 
I am a GSSOC's contributor

**Comment by andoriyaprashant** [comment]
Go ahead @krishitapandey

**Comment by andoriyaprashant** [comment]
Any updates @krishitapandey

**Comment by krishitapandey** [comment]
I am working on it I will push it by Friday

**Comment by andoriyaprashant** [comment]
Okay

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant , Can I work on this Issue? I intend to create another issue for the addition of projects extracted from [](https://www.outreachy.org/past-projects/) and complete the UI page for Outreachy via this Issue.

**Comment by VITianLalit** [comment]
I want to work on this issue please assign it to me @andoriyaprashant ??

**Comment by andoriyaprashant** [comment]
@RishavKumarSinha Would you like to work on this issue, or should I assign it to Lalit?

**Comment by RishavKumarSinha** [comment]
> @RishavKumarSinha Would you like to work on this issue, or should I assign it to Lalit?

Yes, I would be more than happy to work on this Issue.
