### ISSUE TITLE
Feat: Creation of new UI for Major league hacking fellowship

### ISSUE THREAD

**Issue by anuragJoshi05** [andoriyaprashant/OpSo#95]
### Describe the feature

I can't see any UI, when I click most of open-source buttons, I will create UI for each of them and contribute to this project.
Firstly, I would like to make for Major league hacking fellowship

### Add ScreenShots

![WhatsApp Image 2024-05-11 at 21 44 51_5dec5cd2](https://github.com/andoriyaprashant/OpSo/assets/148903459/11796a14-615e-4f4c-8b30-e57b6f61ee95)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by Chekka-Mounika** [comment]
I want to work on this . Please assign me

**Comment by Shubham-Zone** [comment]
@andoriyaprashant assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter
